/**:
  ros__parameters:
    poses:
      - initial_pose
      - detecting_pose

    initial_pose:
      arm_lift               :  0.0
      arm_flex               :  0.0
      arm_roll               :  0.0
      wrist_flex             : -1.57
      wrist_roll             :  0.0
      head_pan               :  0.0
      head_tilt              :  0.0
      hand_l_spring_proximal :  0.0
      # hand_r_spring_proximal :  0.0

    detecting_pose:
      arm_lift               :  0.5
      arm_flex               :  0.0
      arm_roll               :  0.0
      wrist_flex             : -1.57
      wrist_roll             :  0.0
      head_pan               :  0.0
      head_tilt              :  -0.3
      hand_l_spring_proximal :  1.0
      # hand_r_spring_proximal :  0.0
